"""create orders table

Revision ID: 42d84899e59c
Revises: 48c911fc95f3
Create Date: 2021-01-18 14:34:19.080902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42d84899e59c'
down_revision = '48c911fc95f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    orders_table = op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(orders_table, [
        {'employee_id': 1, 'table_id': 6, 'finished': False},
        {'employee_id': 1, 'table_id': 10, 'finished': True},
        {'employee_id': 1, 'table_id': 7, 'finished': False},
        {'employee_id': 1, 'table_id': 3, 'finished': True},
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
