"""create tables table

Revision ID: 71f7db59d970
Revises: 6736558f712a
Create Date: 2021-01-18 15:09:38.973161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71f7db59d970'
down_revision = '6736558f712a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    tables_table = op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )

    op.bulk_insert(tables_table, [
        {'number': 1, 'capacity': 15},
        {'number': 2, 'capacity': 2},
        {'number': 3, 'capacity': 2},
        {'number': 4, 'capacity': 4},
        {'number': 5, 'capacity': 10},
        {'number': 6, 'capacity': 2},
        {'number': 7, 'capacity': 8},
        {'number': 8, 'capacity': 2},
        {'number': 9, 'capacity': 4},
        {'number': 10, 'capacity': 8},
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tables')
    # ### end Alembic commands ###
