"""create employees table

Revision ID: 7108a7d5e64c
Revises: 
Create Date: 2021-01-18 12:21:00.804716

"""
from alembic import op
import sqlalchemy as sa
from werkzeug.security import generate_password_hash, check_password_hash



# revision identifiers, used by Alembic.
revision = '7108a7d5e64c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    employees_table = op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('employee_number', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_number')
    )

    op.bulk_insert(employees_table, [
        {'name': 'Margot', 'employee_number': 1234, 'hashed_password': generate_password_hash('password')},
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    # ### end Alembic commands ###
