"""create menu item types table

Revision ID: ffa1ee37d248
Revises: 7108a7d5e64c
Create Date: 2021-01-18 14:13:14.992621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffa1ee37d248'
down_revision = '7108a7d5e64c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    menu_item_types_table = op.create_table('menu_item_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(menu_item_types_table, [
        {'name': 'Beverages'},
        {'name': 'Entrees'},
        {'name': 'Sides'}
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_item_types')
    # ### end Alembic commands ###
