"""create order details table

Revision ID: f16754f40288
Revises: 42d84899e59c
Create Date: 2021-01-18 14:38:38.153080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f16754f40288'
down_revision = '42d84899e59c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    order_details_table = op.create_table('order_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(order_details_table, [
        {'order_id': 1, 'menu_item_id': 3},
        {'order_id': 2, 'menu_item_id': 2},
        {'order_id': 3, 'menu_item_id': 1},
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_details')
    # ### end Alembic commands ###
