"""create order details table

Revision ID: a8b216c9a036
Revises: 474f12d3d56d
Create Date: 2021-01-18 15:10:56.350991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b216c9a036'
down_revision = '474f12d3d56d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    order_details_table = op.create_table('order_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(order_details_table, [
        {'order_id': 6, 'menu_item_id': 2},
        {'order_id': 4, 'menu_item_id': 4},
        {'order_id': 1, 'menu_item_id': 2},
        {'order_id': 5, 'menu_item_id': 3},
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_details')
    # ### end Alembic commands ###
