"""create menu items table

Revision ID: 11261d3a8154
Revises: 80d5cc3e3a7b
Create Date: 2021-01-18 14:21:20.030769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11261d3a8154'
down_revision = '80d5cc3e3a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    menu_items_table = op.create_table('menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('menu_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
    sa.ForeignKeyConstraint(['menu_type_id'], ['menu_item_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(menu_items_table, [
        {'name': 'French Fries', 'price': 3.50, 'menu_id': 2, 'menu_type_id': 3},
        {'name': 'Dr. Pepper', 'price': 1.00, 'menu_id': 2, 'menu_type_id': 1},
        {'name': 'Jambalaya', 'price': 21.98, 'menu_id': 3, 'menu_type_id': 2},
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_items')
    # ### end Alembic commands ###
