"""create menu table

Revision ID: 80d5cc3e3a7b
Revises: ffa1ee37d248
Create Date: 2021-01-18 14:17:35.845333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d5cc3e3a7b'
down_revision = 'ffa1ee37d248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    menu_table = op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(menu_table, [
        {'name': 'Breakfast'},
        {'name': 'Lunch'},
        {'name': 'Dinner'},
        {'name': 'Dessert'},
        {'name': 'Happy Hour'}
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menus')
    # ### end Alembic commands ###
