"""create orders table

Revision ID: 474f12d3d56d
Revises: 71f7db59d970
Create Date: 2021-01-18 15:10:18.459769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474f12d3d56d'
down_revision = '71f7db59d970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    orders_table = op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(orders_table, [
        {'employee_id': 3, 'table_id': 9, 'finished': False},
        {'employee_id': 1, 'table_id': 6, 'finished': True},
        {'employee_id': 1, 'table_id': 8, 'finished': False},
        {'employee_id': 2, 'table_id': 2, 'finished': False},
        {'employee_id': 2, 'table_id': 3, 'finished': True},
        {'employee_id': 3, 'table_id': 5, 'finished': True},
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
