"""create menu items table

Revision ID: 6736558f712a
Revises: d3664c23ae8c
Create Date: 2021-01-18 15:09:02.269815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6736558f712a'
down_revision = 'd3664c23ae8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    menu_items_table = op.create_table('menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('menu_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
    sa.ForeignKeyConstraint(['menu_type_id'], ['menu_item_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(menu_items_table, [
        {'name': 'French Fries', 'price': 4.50, 'menu_id': 2, 'menu_type_id': 3},
        {'name': 'Denver Omelette', 'price': 11.00, 'menu_id': 1, "menu_type_id": 2},
        {'name': 'Espresso Martini', 'price': 8.00, 'menu_id': 4, "menu_type_id": 4},
        {'name': 'Prime Rib', 'price': 16.00, 'menu_id': 3, "menu_type_id": 2},
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_items')
    # ### end Alembic commands ###
