"""create menu item types table

Revision ID: d3664c23ae8c
Revises: dfbf3b5f15ee
Create Date: 2021-01-18 15:08:27.430311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3664c23ae8c'
down_revision = 'dfbf3b5f15ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    menu_item_types_table = op.create_table('menu_item_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(menu_item_types_table, [
        {'name': 'Non-Alcoholic Drinks'},
        {'name': 'Entrees'},
        {'name': 'Sides'},
        {'name': 'Spirits'},
        {'name': 'Beers'},
        {'name': 'Wines'},
        {'name': 'Appetizers'},
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_item_types')
    # ### end Alembic commands ###
